{
 "title": "Machine Demo Box",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Errors by Device",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  concat('Device ', device) AS metric,\n  count(id) AS \"no of errors\"\nFROM t_error\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1, device,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Errors by status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  state AS metric,\n  count(id) AS \"no of errors\"\nFROM t_error\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Error Resolutions",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  state,\n  count(state)\nFROM t_error\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY state\n"
    }
   ]
  }
 ]
}